### ISSUE TITLE
Basic Application Shell and Architecture (Android)

### ISSUE THREAD

**Issue by adrienshen** [jusaudio/web-react#12]
First we likely want feature parity with the web-app with similar design.

@vlad-ed-git Let's discuss this some more once the initial code is pushed.  👍

**Comment by adrienshen** [comment]
@vlad-ed-git Is this consider finished? Can we close this issue?

If done, I think we can write some helpful documentation in the READ.ME on core technologies used, how to get started, and anything else you think is useful for other devs to know.

**Comment by vlad-ed-git** [comment]
I have updated the project issues tracker.
